### ISSUE TITLE
Getting error on event action 400 Bad Request

### ISSUE THREAD

**Issue by dmiepub** [mgeiss/mifos-twilio-bridge#4]
I have cloned https://github.com/mgeiss/mifos-twilio-bridge and do a gradlew bootRun to start the application.
My mobile number is registered with Twilio trial account
I have added a SMS Bridge webhook template

Hook Name: | Twilio
-- | --
Status: | true
Activation Date: | [2018,7,13]
Updated On: | [2018,7,14]
Events: | DEPOSIT - SAVINGSACCOUNT                                                                                                                                                                    CREATE - CLIENT                                                                                                                                                                    WITHDRAW - SAVINGSACCOUNT                                                                                                                                                                    REPAYMENT - LOAN | DEPOSIT - SAVINGSACCOUNT | CREATE - CLIENT | WITHDRAW - SAVINGSACCOUNT | REPAYMENT - LOAN
DEPOSIT - SAVINGSACCOUNT
CREATE - CLIENT
WITHDRAW - SAVINGSACCOUNT
REPAYMENT - LOAN
Payload URL: | http://localhost:9191/modules/sms
Phone Number: | +9195xxxxxx80
SMS Provider: | Twilio
SMS Provider Account Id: | xxxxxxxxxxxxxxxxxxxxxxxxx
SMS Provider Token: | xxxxxxxxxxxxxxxxxxxxxxxxx

Errors on getting Events:

`Exception in thread "SimpleAsyncTaskExecutor-156" retrofit.RetrofitError: 400 Bad Request
	at retrofit.RetrofitError.httpError(RetrofitError.java:39)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:382)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
	at com.sun.proxy.$Proxy721.sendSmsBridgeConfigRequest(Unknown Source)
	at org.apache.fineract.infrastructure.hooks.processor.TwilioHookProcessor.sendRequest(TwilioHookProcessor.java:96)
	at org.apache.fineract.infrastructure.hooks.processor.TwilioHookProcessor.process(TwilioHookProcessor.java:72)
	at org.apache.fineract.infrastructure.hooks.listener.FineractHookListener.onApplicationEvent(FineractHookListener.java:75)
	at org.apache.fineract.infrastructure.hooks.listener.FineractHookListener.onApplicationEvent(FineractHookListener.java:36)
	at org.springframework.context.event.SimpleApplicationEventMulticaster$1.run(SimpleApplicationEventMulticaster.java:93)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by dmiepub** [comment]
I google 'retrofit.RetrofitError'error and found the following search result:
https://github.com/kaaes/spotify-web-api-android/issues/82
